import { WordCard } from './types';

// Helper to create the list cleanly
const createList = (): WordCard[] => {
  const rawData = [
    { da: 'Tandbørste', en: 'Toothbrush', kw: 'toothbrush' },
    { da: 'Kaffemaskine', en: 'Coffee Machine', kw: 'coffee' },
    { da: 'Regnbue', en: 'Rainbow', kw: 'rainbow' },
    { da: 'Elevator', en: 'Elevator', kw: 'elevator' },
    { da: 'Pizza', en: 'Pizza', kw: 'pizza' },
    { da: 'Cykel', en: 'Bicycle', kw: 'bicycle' },
    { da: 'Fjernbetjening', en: 'Remote Control', kw: 'remote' },
    { da: 'Isbjørn', en: 'Polar Bear', kw: 'polarbear' },
    { da: 'Mobiltelefon', en: 'Mobile Phone', kw: 'smartphone' },
    { da: 'Spejl', en: 'Mirror', kw: 'mirror' },
    { da: 'Hovedpude', en: 'Pillow', kw: 'pillow' },
    { da: 'Paraply', en: 'Umbrella', kw: 'umbrella' },
    { da: 'Lommelygte', en: 'Flashlight', kw: 'flashlight' },
    { da: 'Skraldespand', en: 'Trash Can', kw: 'trash' },
    { da: 'Vækkeur', en: 'Alarm Clock', kw: 'clock' },
    { da: 'Køleskab', en: 'Fridge', kw: 'fridge' },
    { da: 'Tandlæge', en: 'Dentist', kw: 'dentist' },
    { da: 'Bibliotek', en: 'Library', kw: 'library' },
    { da: 'Sok', en: 'Sock', kw: 'sock' },
    { da: 'Kuffert', en: 'Suitcase', kw: 'suitcase' },
    { da: 'Popcorn', en: 'Popcorn', kw: 'popcorn' },
    { da: 'Supermarked', en: 'Supermarket', kw: 'supermarket' },
    { da: 'Skateboard', en: 'Skateboard', kw: 'skateboard' },
    { da: 'Solbriller', en: 'Sunglasses', kw: 'sunglasses' },
    { da: 'Pandekage', en: 'Pancake', kw: 'pancake' },
    { da: 'Postkasse', en: 'Mailbox', kw: 'mailbox' },
    { da: 'Myg', en: 'Mosquito', kw: 'insect' },
    { da: 'Sæbeboble', en: 'Soap Bubble', kw: 'bubble' },
    { da: 'Sandwich', en: 'Sandwich', kw: 'sandwich' },
    { da: 'Rygsæk', en: 'Backpack', kw: 'backpack' },
    { da: 'Måne', en: 'Moon', kw: 'moon' },
    { da: 'Tandstikker', en: 'Toothpick', kw: 'wood' },
    { da: 'Svømmehal', en: 'Swimming Pool', kw: 'pool' },
    { da: 'GPS', en: 'GPS', kw: 'map' },
    { da: 'Hæveautomat', en: 'ATM', kw: 'money' },
    { da: 'Badeand', en: 'Rubber Duck', kw: 'duck' },
    { da: 'Løbehjul', en: 'Scooter', kw: 'scooter' },
    { da: 'Kaktus', en: 'Cactus', kw: 'cactus' },
    { da: 'Dyne', en: 'Duvet', kw: 'bed' },
    { da: 'Skolebus', en: 'School Bus', kw: 'bus' },
    { da: 'Ketchup', en: 'Ketchup', kw: 'ketchup' },
    { da: 'Mikrobølgeovn', en: 'Microwave', kw: 'microwave' },
    { da: 'Selfie', en: 'Selfie', kw: 'camera' },
    { da: 'Hængekøje', en: 'Hammock', kw: 'hammock' },
    { da: 'Trafiklys', en: 'Traffic Light', kw: 'traffic' },
    { da: 'Tandtråd', en: 'Dental Floss', kw: 'dental' },
    { da: 'Pandebånd', en: 'Headband', kw: 'sport' },
    { da: 'Ost', en: 'Cheese', kw: 'cheese' },
    { da: 'Termokande', en: 'Thermos', kw: 'coffee' },
    { da: 'Myresluger', en: 'Anteater', kw: 'animal' },
    { da: 'Kæledyr', en: 'Pet', kw: 'pet' },
    { da: 'Nøgler', en: 'Keys', kw: 'keys' },
    { da: 'Støvsuger', en: 'Vacuum Cleaner', kw: 'cleaning' },
    { da: 'Sovemaske', en: 'Sleep Mask', kw: 'sleep' },
    { da: 'Grill', en: 'Grill', kw: 'bbq' },
    { da: 'Pingvin', en: 'Penguin', kw: 'penguin' },
    { da: 'Kalender', en: 'Calendar', kw: 'calendar' },
    { da: 'Skorsten', en: 'Chimney', kw: 'house' },
    { da: 'Snebold', en: 'Snowball', kw: 'snow' },
    { da: 'Legetøj', en: 'Toy', kw: 'toy' },
    { da: 'Bibliotekar', en: 'Librarian', kw: 'book' },
    { da: 'Slips', en: 'Tie', kw: 'suit' },
    { da: 'Lygtepæl', en: 'Lamppost', kw: 'light' },
    { da: 'Smoothie', en: 'Smoothie', kw: 'drink' },
    { da: 'Bål', en: 'Bonfire', kw: 'fire' },
    { da: 'Trampolin', en: 'Trampoline', kw: 'jump' },
    { da: 'Post-it', en: 'Sticky Note', kw: 'note' },
    { da: 'Tyggegummi', en: 'Chewing Gum', kw: 'candy' },
    { da: 'Kamera', en: 'Camera', kw: 'camera' },
    { da: 'Gulerod', en: 'Carrot', kw: 'carrot' },
    { da: 'Fjernsyn', en: 'Television', kw: 'tv' },
    { da: 'Tandkrus', en: 'Toothbrush Cup', kw: 'bathroom' },
    { da: 'Bjerg', en: 'Mountain', kw: 'peak' },
    { da: 'Madpakke', en: 'Lunchbox', kw: 'lunch' },
    { da: 'Rutsjebane', en: 'Slide', kw: 'playground' },
    { da: 'Håndjern', en: 'Handcuffs', kw: 'police' },
    { da: 'Pindsvin', en: 'Hedgehog', kw: 'animal' },
    { da: 'Skakbrik', en: 'Chess Piece', kw: 'chess' },
    { da: 'Cirkus', en: 'Circus', kw: 'circus' },
    { da: 'Skildpadde', en: 'Turtle', kw: 'turtle' },
    { da: 'Lommekniv', en: 'Pocket Knife', kw: 'tool' },
    { da: 'Briller', en: 'Glasses', kw: 'glasses' },
    { da: 'Mønt', en: 'Coin', kw: 'money' },
    { da: 'Skatteø', en: 'Treasure Island', kw: 'island' },
    { da: 'Kagedåse', en: 'Cookie Jar', kw: 'cookie' },
    { da: 'Vindmølle', en: 'Windmill', kw: 'wind' },
    { da: 'Sovepose', en: 'Sleeping Bag', kw: 'camping' },
    { da: 'Regnjakke', en: 'Raincoat', kw: 'rain' },
    { da: 'Tandhjul', en: 'Gear', kw: 'gear' },
    { da: 'Kælk', en: 'Sled', kw: 'snow' },
    { da: 'Skæg', en: 'Beard', kw: 'face' },
    { da: 'Timeglas', en: 'Hourglass', kw: 'time' },
    { da: 'Fodspor', en: 'Footprint', kw: 'sand' },
    { da: 'Magnet', en: 'Magnet', kw: 'magnet' },
    { da: 'Peberkværn', en: 'Pepper Mill', kw: 'spice' },
    { da: 'Satellit', en: 'Satellite', kw: 'space' },
    { da: 'Bølge', en: 'Wave', kw: 'ocean' },
    { da: 'Tryllekunstner', en: 'Magician', kw: 'magic' },
  ];

  return rawData.map((item, index) => ({
    id: index,
    da: item.da,
    en: item.en,
    imageKeyword: item.kw
  }));
};

export const WORD_LIST = createList();
export const GAME_DURATION_SECONDS = 30;
export const AUDIO_ALERT_THRESHOLD = 5;
