import { WordCard } from './types';

// Helper to create the list cleanly
const createList = (): WordCard[] => {
  const rawData = [
    { da: 'Tandbørste', en: 'Toothbrush', kw: 'toothbrush' },
    { da: 'Kaffemaskine', en: 'Coffee Machine', kw: 'coffee' },
    { da: 'Regnbue', en: 'Rainbow', kw: 'rainbow' },
    { da: 'Elevator', en: 'Elevator', kw: 'elevator' },
    { da: 'Pizza', en: 'Pizza', kw: 'pizza' },
    { da: 'Cykel', en: 'Bicycle', kw: 'bicycle' },
    { da: 'Fjernbetjening', en: 'Remote Control', kw: 'remote' },
    { da: 'Isbjørn', en: 'Polar Bear', kw: 'polarbear' },
    { da: 'Mobiltelefon', en: 'Mobile Phone', kw: 'smartphone' },
    { da: 'Spejl', en: 'Mirror', kw: 'mirror' },
    { da: 'Hovedpude', en: 'Pillow', kw: 'pillow' },
    { da: 'Paraply', en: 'Umbrella', kw: 'umbrella' },
    { da: 'Lommelygte', en: 'Flashlight', kw: 'flashlight' },
    { da: 'Skraldespand', en: 'Trash Can', kw: 'trash' },
    { da: 'Vækkeur', en: 'Alarm Clock', kw: 'clock' },
    { da: 'Køleskab', en: 'Fridge', kw: 'fridge' },
    { da: 'Tandlæge', en: 'Dentist', kw: 'dentist' },
    { da: 'Bibliotek', en: 'Library', kw: 'library' },
    { da: 'Sok', en: 'Sock', kw: 'sock' },
    { da: 'Kuffert', en: 'Suitcase', kw: 'suitcase' },
    { da: 'Popcorn', en: 'Popcorn', kw: 'popcorn' },
    { da: 'Supermarked', en: 'Supermarket', kw: 'supermarket' },
    { da: 'Skateboard', en: 'Skateboard', kw: 'skateboard' },
    { da: 'Solbriller', en: 'Sunglasses', kw: 'sunglasses' },
    { da: 'Pandekage', en: 'Pancake', kw: 'pancake' },
    { da: 'Postkasse', en: 'Mailbox', kw: 'mailbox' },
    { da: 'Myg', en: 'Mosquito', kw: 'insect' },
    { da: 'Sæbeboble', en: 'Soap Bubble', kw: 'bubble' },
    { da: 'Sandwich', en: 'Sandwich', kw: 'sandwich' },
    { da: 'Rygsæk', en: 'Backpack', kw: 'backpack' },
    { da: 'Måne', en: 'Moon', kw: 'moon' },
    { da: 'Tandstikker', en: 'Toothpick', kw: 'wood' },
    { da: 'Svømmehal', en: 'Swimming Pool', kw: 'pool' },
    { da: 'GPS', en: 'GPS', kw: 'map' },
    { da: 'Hæveautomat', en: 'ATM', kw: 'money' },
    { da: 'Badeand', en: 'Rubber Duck', kw: 'duck' },
    { da: 'Løbehjul', en: 'Scooter', kw: 'scooter' },
    { da: 'Kaktus', en: 'Cactus', kw: 'cactus' },
    { da: 'Dyne', en: 'Duvet', kw: 'bed' },
    { da: 'Skolebus', en: 'School Bus', kw: 'bus' },
    { da: 'Ketchup', en: 'Ketchup', kw: 'ketchup' },
    { da: 'Mikrobølgeovn', en: 'Microwave', kw: 'microwave' },
    { da: 'Selfie', en: 'Selfie', kw: 'camera' },
    { da: 'Hængekøje', en: 'Hammock', kw: 'hammock' },
    { da: 'Trafiklys', en: 'Traffic Light', kw: 'traffic' },
    { da: 'Tandtråd', en: 'Dental Floss', kw: 'dental' },
    { da: 'Pandebånd', en: 'Headband', kw: 'sport' },
    { da: 'Ost', en: 'Cheese', kw: 'cheese' },
    { da: 'Termokande', en: 'Thermos', kw: 'coffee' },
    { da: 'Myresluger', en: 'Anteater', kw: 'animal' },
    { da: 'Kæledyr', en: 'Pet', kw: 'pet' },
    { da: 'Nøgler', en: 'Keys', kw: 'keys' },
    { da: 'Støvsuger', en: 'Vacuum Cleaner', kw: 'cleaning' },
    { da: 'Sovemaske', en: 'Sleep Mask', kw: 'sleep' },
    { da: 'Grill', en: 'Grill', kw: 'bbq' },
    { da: 'Pingvin', en: 'Penguin', kw: 'penguin' },
    { da: 'Kalender', en: 'Calendar', kw: 'calendar' },
    { da: 'Skorsten', en: 'Chimney', kw: 'house' },
    { da: 'Snebold', en: 'Snowball', kw: 'snow' },
    { da: 'Legetøj', en: 'Toy', kw: 'toy' },
    { da: 'Bibliotekar', en: 'Librarian', kw: 'book' },
    { da: 'Slips', en: 'Tie', kw: 'suit' },
    { da: 'Lygtepæl', en: 'Lamppost', kw: 'light' },
    { da: 'Smoothie', en: 'Smoothie', kw: 'drink' },
    { da: 'Bål', en: 'Bonfire', kw: 'fire' },
    { da: 'Trampolin', en: 'Trampoline', kw: 'jump' },
    { da: 'Post-it', en: 'Sticky Note', kw: 'note' },
    { da: 'Tyggegummi', en: 'Chewing Gum', kw: 'candy' },
    { da: 'Kamera', en: 'Camera', kw: 'camera' },
    { da: 'Gulerod', en: 'Carrot', kw: 'carrot' },
    { da: 'Fjernsyn', en: 'Television', kw: 'tv' },
    { da: 'Tandkrus', en: 'Toothbrush Cup', kw: 'bathroom' },
    { da: 'Bjerg', en: 'Mountain', kw: 'peak' },
    { da: 'Madpakke', en: 'Lunchbox', kw: 'lunch' },
    { da: 'Rutsjebane', en: 'Slide', kw: 'playground' },
    { da: 'Håndjern', en: 'Handcuffs', kw: 'police' },
    { da: 'Pindsvin', en: 'Hedgehog', kw: 'animal' },
    { da: 'Skakbrik', en: 'Chess Piece', kw: 'chess' },
    { da: 'Cirkus', en: 'Circus', kw: 'circus' },
    { da: 'Skildpadde', en: 'Turtle', kw: 'turtle' },
    { da: 'Lommekniv', en: 'Pocket Knife', kw: 'tool' },
    { da: 'Briller', en: 'Glasses', kw: 'glasses' },
    { da: 'Mønt', en: 'Coin', kw: 'money' },
    { da: 'Skatteø', en: 'Treasure Island', kw: 'island' },
    { da: 'Kagedåse', en: 'Cookie Jar', kw: 'cookie' },
    { da: 'Vindmølle', en: 'Windmill', kw: 'wind' },
    { da: 'Sovepose', en: 'Sleeping Bag', kw: 'camping' },
    { da: 'Regnjakke', en: 'Raincoat', kw: 'rain' },
    { da: 'Tandhjul', en: 'Gear', kw: 'gear' },
    { da: 'Kælk', en: 'Sled', kw: 'snow' },
    { da: 'Skæg', en: 'Beard', kw: 'face' },
    { da: 'Timeglas', en: 'Hourglass', kw: 'time' },
    { da: 'Fodspor', en: 'Footprint', kw: 'sand' },
    { da: 'Magnet', en: 'Magnet', kw: 'magnet' },
    { da: 'Peberkværn', en: 'Pepper Mill', kw: 'spice' },
    { da: 'Satellit', en: 'Satellite', kw: 'space' },
    { da: 'Bølge', en: 'Wave', kw: 'ocean' },
    { da: 'Tryllekunstner', en: 'Magician', kw: 'magic' },
    { da: 'Banan', en: 'Banana', kw: 'banana' },
    { da: 'Æble', en: 'Apple', kw: 'apple' },
    { da: 'Appelsin', en: 'Orange', kw: 'orange' },
    { da: 'Jordbær', en: 'Strawberry', kw: 'strawberry' },
    { da: 'Vandmelon', en: 'Watermelon', kw: 'watermelon' },
    { da: 'Citron', en: 'Lemon', kw: 'lemon' },
    { da: 'Kartoffel', en: 'Potato', kw: 'potato' },
    { da: 'Tomat', en: 'Tomato', kw: 'tomato' },
    { da: 'Broccoli', en: 'Broccoli', kw: 'broccoli' },
    { da: 'Brød', en: 'Bread', kw: 'bread' },
    { da: 'Mælk', en: 'Milk', kw: 'milk' },
    { da: 'Æg', en: 'Egg', kw: 'egg' },
    { da: 'Is', en: 'Ice Cream', kw: 'icecream' },
    { da: 'Chokolade', en: 'Chocolate', kw: 'chocolate' },
    { da: 'Stol', en: 'Chair', kw: 'chair' },
    { da: 'Bord', en: 'Table', kw: 'table' },
    { da: 'Seng', en: 'Bed', kw: 'bed' },
    { da: 'Lampe', en: 'Lamp', kw: 'lamp' },
    { da: 'Bog', en: 'Book', kw: 'book' },
    { da: 'Blyant', en: 'Pencil', kw: 'pencil' },
    { da: 'Saks', en: 'Scissors', kw: 'scissors' },
    { da: 'Lineal', en: 'Ruler', kw: 'ruler' },
    { da: 'Viskelæder', en: 'Eraser', kw: 'eraser' },
    { da: 'Tavle', en: 'Blackboard', kw: 'blackboard' },
    { da: 'Taske', en: 'Bag', kw: 'bag' },
    { da: 'Sko', en: 'Shoe', kw: 'shoe' },
    { da: 'T-shirt', en: 'T-shirt', kw: 'tshirt' },
    { da: 'Jakke', en: 'Jacket', kw: 'jacket' },
    { da: 'Hat', en: 'Hat', kw: 'hat' },
    { da: 'Ur', en: 'Watch', kw: 'watch' },
    { da: 'Ring', en: 'Ring', kw: 'ring' },
    { da: 'Bil', en: 'Car', kw: 'car' },
    { da: 'Bus', en: 'Bus', kw: 'bus' },
    { da: 'Tog', en: 'Train', kw: 'train' },
    { da: 'Fly', en: 'Airplane', kw: 'airplane' },
    { da: 'Båd', en: 'Boat', kw: 'boat' },
    { da: 'Helikopter', en: 'Helicopter', kw: 'helicopter' },
    { da: 'Hund', en: 'Dog', kw: 'dog' },
    { da: 'Kat', en: 'Cat', kw: 'cat' },
    { da: 'Kanin', en: 'Rabbit', kw: 'rabbit' },
    { da: 'Fugl', en: 'Bird', kw: 'bird' },
    { da: 'Fisk', en: 'Fish', kw: 'fish' },
    { da: 'Hest', en: 'Horse', kw: 'horse' },
    { da: 'Ko', en: 'Cow', kw: 'cow' },
    { da: 'Får', en: 'Sheep', kw: 'sheep' },
    { da: 'Gris', en: 'Pig', kw: 'pig' },
    { da: 'Løve', en: 'Lion', kw: 'lion' },
    { da: 'Elefant', en: 'Elephant', kw: 'elephant' },
    { da: 'Giraf', en: 'Giraffe', kw: 'giraffe' },
    { da: 'Abe', en: 'Monkey', kw: 'monkey' },
    { da: 'Opvaskemaskine', en: 'Dishwasher', kw: 'dishwasher' },
    { da: 'Brødrister', en: 'Toaster', kw: 'toaster' },
    { da: 'Gaffel', en: 'Fork', kw: 'fork' },
    { da: 'Kniv', en: 'Knife', kw: 'knife' },
    { da: 'Ske', en: 'Spoon', kw: 'spoon' },
    { da: 'Tallerken', en: 'Plate', kw: 'plate' },
    { da: 'Kop', en: 'Cup', kw: 'cup' },
    { da: 'Hårtørrer', en: 'Hair dryer', kw: 'hairdryer' },
    { da: 'Badekar', en: 'Bathtub', kw: 'bathtub' },
    { da: 'Sofa', en: 'Sofa', kw: 'sofa' },
    { da: 'Pære', en: 'Pear', kw: 'pear' },
    { da: 'Vindruer', en: 'Grapes', kw: 'grapes' },
    { da: 'Ananas', en: 'Pineapple', kw: 'pineapple' },
    { da: 'Agurk', en: 'Cucumber', kw: 'cucumber' },
    { da: 'Suppe', en: 'Soup', kw: 'soup' },
    { da: 'Muffin', en: 'Muffin', kw: 'muffin' },
    { da: 'Juice', en: 'Juice', kw: 'juice' },
    { da: 'Smør', en: 'Butter', kw: 'butter' },
    { da: 'Bukser', en: 'Pants', kw: 'pants' },
    { da: 'Trøje', en: 'Sweater', kw: 'sweater' },
    { da: 'Handsker', en: 'Gloves', kw: 'gloves' },
    { da: 'Hårbørste', en: 'Hairbrush', kw: 'hairbrush' },
    { da: 'Sæbe', en: 'Soap', kw: 'soap' },
    { da: 'Håndklæde', en: 'Towel', kw: 'towel' },
    { da: 'Sol', en: 'Sun', kw: 'sun' },
    { da: 'Sky', en: 'Cloud', kw: 'cloud' },
    { da: 'Stjerne', en: 'Star', kw: 'star' },
    { da: 'Træ', en: 'Tree', kw: 'tree' },
    { da: 'Blomst', en: 'Flower', kw: 'flower' },
    { da: 'Skov', en: 'Forest', kw: 'forest' },
    { da: 'Sten', en: 'Stone', kw: 'stone' },
    { da: 'Snefnug', en: 'Snowflake', kw: 'snowflake' },
    { da: 'Lastbil', en: 'Truck', kw: 'truck' },
    { da: 'Motorcykel', en: 'Motorcycle', kw: 'motorcycle' },
    { da: 'Ubåd', en: 'Submarine', kw: 'submarine' },
    { da: 'Traktor', en: 'Tractor', kw: 'tractor' },
    { da: 'Hammer', en: 'Hammer', kw: 'hammer' },
    { da: 'Skruetrækker', en: 'Screwdriver', kw: 'screwdriver' },
    { da: 'Søm', en: 'Nail', kw: 'nail' },
    { da: 'Skruenøgle', en: 'Wrench', kw: 'wrench' },
    { da: 'Ugle', en: 'Owl', kw: 'owl' },
    { da: 'Ræv', en: 'Fox', kw: 'fox' },
    { da: 'Egern', en: 'Squirrel', kw: 'squirrel' },
    { da: 'Mus', en: 'Mouse', kw: 'mouse' },
    { da: 'Bjørn', en: 'Bear', kw: 'bear' },
    { da: 'Haj', en: 'Shark', kw: 'shark' },
    { da: 'Hval', en: 'Whale', kw: 'whale' },
    { da: 'Delfin', en: 'Dolphin', kw: 'dolphin' },
    { da: 'Sommerfugl', en: 'Butterfly', kw: 'butterfly' },
    { da: 'Mariehøne', en: 'Ladybug', kw: 'ladybug' },
  ];

  return rawData.map((item, index) => ({
    id: index,
    da: item.da,
    en: item.en,
    imageKeyword: item.kw
  }));
};

export const WORD_LIST = createList();
export const GAME_DURATION_SECONDS = 30;
export const AUDIO_ALERT_THRESHOLD = 5;
